-- Create clinics table
CREATE TABLE public.clinics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    address text NOT NULL,
    phone text,
    email text,
    license_number text,
    tax_id text,
    status text NOT NULL DEFAULT 'pending_verification',
    settings jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Add RLS policies for clinics
ALTER TABLE public.clinics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public clinics are viewable by everyone" ON public.clinics
    FOR SELECT USING (true);

CREATE POLICY "Users can insert their own clinic" ON public.clinics
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can update their own clinic" ON public.clinics
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM clinic_users
            WHERE clinic_users.clinic_id = id
            AND clinic_users.user_id = auth.uid()
            AND clinic_users.role = 'admin'
        )
    );

-- Create clinic_users table
CREATE TABLE public.clinic_users (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES auth.users NOT NULL,
    clinic_id bigint REFERENCES public.clinics NOT NULL,
    role text NOT NULL,
    full_name text NOT NULL,
    email text NOT NULL,
    phone text,
    specialization text, -- For doctors/nurses
    license_number text, -- For doctors
    status text NOT NULL DEFAULT 'pending',
    settings jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    UNIQUE(user_id, clinic_id)
);

-- Add RLS policies for clinic_users
ALTER TABLE public.clinic_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their clinic's staff" ON public.clinic_users
    FOR SELECT USING (
        clinic_id IN (
            SELECT clinic_id FROM clinic_users
            WHERE user_id = auth.uid()
        )
    );

CREATE POLICY "Admins can insert staff" ON public.clinic_users
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM clinic_users
            WHERE clinic_users.clinic_id = clinic_id
            AND clinic_users.user_id = auth.uid()
            AND clinic_users.role = 'admin'
        )
    );

CREATE POLICY "Admins can update staff" ON public.clinic_users
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM clinic_users
            WHERE clinic_users.clinic_id = clinic_id
            AND clinic_users.user_id = auth.uid()
            AND clinic_users.role = 'admin'
        )
    );

-- Create role_permissions table for granular access control
CREATE TABLE public.role_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role text NOT NULL,
    resource text NOT NULL,
    action text NOT NULL,
    conditions jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(role, resource, action)
);

-- Insert default role permissions
INSERT INTO public.role_permissions (role, resource, action) VALUES
-- Admin permissions
('admin', 'clinic', 'manage'),
('admin', 'staff', 'manage'),
('admin', 'patients', 'manage'),
('admin', 'appointments', 'manage'),
('admin', 'reports', 'view'),

-- Doctor permissions
('doctor', 'patients', 'view'),
('doctor', 'patients', 'update'),
('doctor', 'appointments', 'view'),
('doctor', 'appointments', 'manage'),
('doctor', 'medical_records', 'manage'),
('doctor', 'prescriptions', 'manage'),

-- Nurse permissions
('nurse', 'patients', 'view'),
('nurse', 'patients', 'update'),
('nurse', 'appointments', 'view'),
('nurse', 'vital_signs', 'manage'),
('nurse', 'medical_records', 'view'),

-- Receptionist permissions
('receptionist', 'patients', 'manage'),
('receptionist', 'appointments', 'manage'),
('receptionist', 'billing', 'manage');

-- Function to check if a user has permission
CREATE OR REPLACE FUNCTION public.has_permission(p_user_id uuid, p_resource text, p_action text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM clinic_users cu
    JOIN role_permissions rp ON cu.role = rp.role
    WHERE cu.user_id = p_user_id
    AND rp.resource = p_resource
    AND rp.action = p_action
    AND cu.status = 'active'
  );
END;
$$;